<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtm.proto

namespace DtmClient\Grpc\Message;

/**
 * The dtm service definition.
 *
 * Protobuf type <code>dtm.Dtm</code>
 */
interface DtmInterface
{
    /**
     * Method <code>newGid</code>
     *
     * @param \Google\Protobuf\GPBEmpty $request
     * @return \DtmClient\Grpc\Message\DtmGidReply
     */
    public function newGid(\Google\Protobuf\GPBEmpty $request);

    /**
     * Method <code>submit</code>
     *
     * @param \DtmClient\Grpc\Message\DtmRequest $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function submit(\DtmClient\Grpc\Message\DtmRequest $request);

    /**
     * Method <code>prepare</code>
     *
     * @param \DtmClient\Grpc\Message\DtmRequest $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function prepare(\DtmClient\Grpc\Message\DtmRequest $request);

    /**
     * Method <code>abort</code>
     *
     * @param \DtmClient\Grpc\Message\DtmRequest $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function abort(\DtmClient\Grpc\Message\DtmRequest $request);

    /**
     * Method <code>registerBranch</code>
     *
     * @param \DtmClient\Grpc\Message\DtmBranchRequest $request
     * @return \Google\Protobuf\GPBEmpty
     */
    public function registerBranch(\DtmClient\Grpc\Message\DtmBranchRequest $request);

}

